ORG_COMMON_NAME='Liquid Labs'
ORG_GITHUB_NAME='Liquid-Labs'
ORG_LEGAL_NAME='Liquid Labs, LLC'
ORG_ADDRESS='907 Isle of Man Ct
Pflugerville, TX 78660'
ORG_NAICS='1'
ORG_NPM_SCOPE='liquid-labs'
ORG_NPM_REGISTRY='https://registry.npmjs.org/'
ORG_SENSITIVE_REPO='@liquid-labs/Liquid-Labs-sensitive'
# Policy settings
ORG_POLICY_REPO='@liquid-labs/Liquid-Labs'

# Ops settings
GEN_SEC_LVL=3 # high

HAS_TECHNICAL_OPS=1
DEVELOPS_APPS=1

HAS_NETWORK=1
HAS_SENSITIVE_NETWORK=1
HAS_SENSITIVE_PHYSICAL_NETWORK=1
HAS_SENSITIVE_VIRTUAL_NETWORK=1

# Compliance settings
HAS_CARDHOLDER_DATA=0
AUTOMATED_NETWORK_LOG_REVIEWS=0
SUPPORTS_AUTOMATED_TESTING=1
TRACKS_APPROVED_TECHNOLOGIES=0
USES_RELEASE_NOTES=1
HAS_PRODUCT_STRATEGY_COMMITTEE=0
USES_RELEASE_MANAGER=0

# Process config
USES_MERGE_MASTER=0

PRODUCTION_NETWORK_DIAGRAM='https://drive.google.com/open?id=1mF9MKOsc3XkFgiNPxGYWBUrV0RG2ksfO'

# Tools
USES_LIQ=1
USES_AUTOMATED_LINTING=1
TASK_MANAGER='GitHub'
TASKS_AND_ISSUES_COEXIST=1
TASKS_LIMITED_TO_A_SINGLE_PROJECT=1

# Policy overrides
TASK_MANAGEMENT_IMPLEMENTATION_DESCRIPTION=0
